update setup file

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,30 +1,59 @@
 #!/usr/bin/env bash
 
-# if any command in script gives an exit status >0 it'll exit immediately
-set -e
+################################################################################
+# Title: MacOS dotfiles bootstrap script
+# Description: This script sets up a new MacOS system with the user's desired
+#              configuration files, programs and tools. It does so by installing
+#              Homebrew, checking for Rosetta 2 (if applicable), installing
+#              packages and apps from a Brewfile, installing Oh My Zsh, the
+#              Powerlevel10k zsh theme, additional zsh plugins and linking
+#              custom configuration files. It also adds asdf version manager
+#              plugins and restores configs with mackup.
+#
+# Author: Thomas Hexton
+# Date: April 2023
+# Version: 1
+# Usage: Run the script with ./bootstrap.sh
+#
+# Notes:
+#  - This script requires a Mac using Intel CPU or Apple Silicon.
+#  - This script should be run with administrator privileges.
+#  - This script is opinionated and tailored to the author's preferences.
+#
+################################################################################
 
-echo "Settin' up..."
+# Open log file for writing and append current date/time
+LOGFILE="$HOME/.bootstrap.log"
+printf "$(date): Starting bootstrap script..." | tee -a "$LOGFILE"
+
+# This will cause the script to exit immediately if any command returns a non-zero exit status.
+# It will also cause the script to exit if any unset variable is used,
+# and will cause pipes to exit with a non-zero status if any command in the pipe fails.
+set -euo pipefail
+
+printf "Bootstrapping..."
 
 WORKDIR=$(pwd)
 REPO_NAME="dotfiles-m1"
 
 # Ask for the administrator password upfront
+printf "Requesting sudo privileges..."
 sudo -v
 
-# Keep-alive: update existing `sudo` time stamp until `setup` has finished
+# Keep-alive: update existing `sudo` time stamp until `bootstrap` script has finished
 while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 
-echo "Installing Homebrew"
+printf "Installing Homebrew"
 
 I_INSTALL_LOC=/usr/local/bin/brew
 A_INSTALL_LOC=/opt/homebrew/bin/brew
 
-# checks which hardware the script has been called on
+# Checks which hardware the script has been called on
 case $(uname -m) in
   "x86_64")
-    echo "Intel hardware detected."
+    printf "Intel hardware detected."
     if [[ ! -f "$I_INSTALL_LOC" ]]; then
-      echo "Installing x86 Homebrew ..."
+      printf "Installing x86 Homebrew ..."
       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
     else
       brew update
@@ -32,54 +61,59 @@ case $(uname -m) in
   ;;
 
   "arm64")
-    echo "Apple Silicon hardware detected."
-    # first, install arm64 version
+    printf "Apple Silicon hardware detected."
+    # First, install arm64 version
     if [[ ! -f "$A_INSTALL_LOC" ]]; then
-      echo "Installing arm64 Homebrew ..."
+      printf "Installing arm64 Homebrew ..."
       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/$USER/.zprofile
+      printf 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/$USER/.zprofile
       eval "$(/opt/homebrew/bin/brew shellenv)"
     else
-      echo "arm64 Homebrew already installed, updating ..."
+      printf "arm64 Homebrew already installed, updating ..."
       brew update
     fi
 
-    # # second, install x86 version to support packages without Apple Silicon variant
-    # if [[ ! -f "$I_INSTALL_LOC" ]]; then
-    #   echo "Installing x86 Homebrew ..."
-    #   arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-    # else
-    #   echo "x86 Homebrew also already installed, updating ..."
-    #   arch -x86_64 $I_INSTALL_LOC update
-    # fi
+    # Add the line to check the `brew doctor` output
+    printf "Checking Homebrew installation with 'brew doctor' ..."
+    if brew doctor &>/dev/null; then
+      printf "Homebrew installation is successful."
+    else
+      printf "Error: Homebrew installation is unsuccessful. Please fix the issues shown by 'brew doctor' and run this script again."
+      exit 1
+    fi
 
-    # echo "Checking if Rosetta 2 is installed..."
-    # if [[ ! -f /Library/Apple/usr/share/rosetta/rosetta ]]; then
-    #   echo "Installing Rosetta 2 ..."
-    #   softwareupdate --install-rosetta --agree-to-license
-    # else
-    #   echo "Roestta 2 already installed."
-    # fi
+    printf "Checking if Rosetta 2 is installed..."
+    if [[ $(sysctl sysctl.proc_translated) == "sysctl.proc_translated: 1" ]]; then
+      printf "Rosetta is already installed."
+    else
+      read -p "Rosetta is not installed. Do you want to install it now? (Y/N) " install_rosetta
+      if [[ $install_rosetta =~ [Yy] ]]; then
+        softwareupdate --install-rosetta --agree-to-license
+        printf "Rosetta has been installed."
+      else
+        printf "Rosetta has not been installed."
+      fi
+    fi
   ;;
 
   *)
-    echo "To install Homebrew, this script requires a Mac using Intel CPU or Apple Silicon."
+    printf "To install Homebrew, this script requires a Mac using Intel CPU or Apple Silicon."
     exit 1
   ;;
 esac
 
 # Install packages and apps from Brewfile
 printf "\n"
-echo "Installing packages and apps with Homebrew..."
+printf "Installing packages and apps with Homebrew..."
 brew bundle --file=dependencies/Brewfile --no-lock --no-upgrade
 
 # Install Oh My Zsh
 if [[ ! -d $HOME/.oh-my-zsh ]]; then
-  echo "Installing Oh My Zsh..."
+  printf "Installing Oh My Zsh..."
   RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
 else
   # Use the inbuilt mechanism to update Oh My Zsh
-  echo "Oh My Zsh already installed, updating..."
+  printf "Oh My Zsh already installed, updating..."
   cd $HOME/.oh-my-zsh
   git pull >/dev/null 2>&1
   cd $WORKDIR
@@ -87,10 +121,10 @@ fi
 
 # Install Powerlevel10k zsh theme
 if [[ ! -d $HOME/.oh-my-zsh/custom/themes/powerlevel10k ]]; then
-  echo "Installing Powerlevel10k zsh theme..."
+  printf "Installing Powerlevel10k zsh theme..."
   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k
 else
-  echo "Powerlevel10k already installed, updating..."
+  printf "Powerlevel10k already installed, updating..."
   cd $HOME/.oh-my-zsh/custom/themes/powerlevel10k
   git pull >/dev/null 2>&1
   cd $WORKDIR
@@ -99,10 +133,10 @@ fi
 # Install additional zsh plugins not included with Oh My Zsh
 for r in zsh-autosuggestions zsh-syntax-highlighting; do
   if [[ ! -d $HOME/.oh-my-zsh/custom/plugins/$r ]]; then
-    echo "Installing $r..."
+    printf "Installing $r..."
     git clone --depth=1 https://github.com/zsh-users/$r $HOME/.oh-my-zsh/custom/plugins/$r
   else
-    echo "$r already installed, updating..."
+    printf "$r already installed, updating..."
     cd $HOME/.oh-my-zsh/custom/plugins/$r
     git pull
     cd $WORKDIR
@@ -115,23 +149,23 @@ done
 #   touch custom/secret.zsh
 # fi
 for file in custom/*; do
-  echo "Creating symbolic linking for $file"
+  printf "Creating symbolic linking for $file"
   ln -sf $WORKDIR/$file $HOME/.oh-my-zsh/$file
 done
 
 # Link ssh config
-echo "Linking ssh config..."
+printf "Linking ssh config..."
 mkdir -p $HOME/.ssh
 ln -sf $WORKDIR/ssh/config $HOME/.ssh/config
 
 # Link $HOME dotfiles
 # TODO: consider how to confirm to XDG file structure
-echo "Linking files to home directory..."
+printf "Linking files to home directory..."
 for file in sym-links/*; do
   if [[ ! -d $file ]]; then
     ln -sf $WORKDIR/$file $HOME/.${file#sym-links/}
   else
-    echo "Ignoring directory $file"
+    printf "Ignoring directory $file"
   fi
 done
 
@@ -143,27 +177,27 @@ fi
 # Install asdf version manager plugins
 for p in $(awk '{print $1}' < sym-links/tool-versions); do
   if [[ ! -d $HOME/.asdf/plugins/$p ]]; then
-    echo "Adding asdf plugin $p..."
+    printf "Adding asdf plugin $p..."
     asdf plugin add $p
   else
-    echo "asdf plugin $p already added, updating..."
+    printf "asdf plugin $p already added, updating..."
     asdf plugin update $p >/dev/null 2>&1
   fi
 done
 
 # Restore configs with mackup
-echo "Linking mackup config..."
+printf "Linking mackup config..."
 if [[ ! -d $HOME/.mackup ]]; then
   mkdir $HOME/.mackup
 fi
 for f in mackup/*; do
   ln -sf $WORKDIR/$f $HOME/.$f
 done
-echo "Restoring files with mackup..."
+printf "Restoring files with mackup..."
 mackup restore -f
 
 if [[ ! -f $HOME/.p10k.zsh ]]; then
-  echo "Setup complete, quit terminal and open iTerm to continue..."
+  printf "Bootstrap complete, quit terminal and open iTerm to continue..."
 else
-  echo "Setup complete."
+  printf "Bootstrap complete."
 fi
